services:
  db:
    image: postgres:18
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql/01_create_schema.sql:/docker-entrypoint-initdb.d/01_create_schema.sql:ro
      - ./sql:/sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./data/raw:/app/data/raw:ro

volumes:
  pgdata:
